service: log-monitor-test

provider:
  name: aws
  runtime: nodejs8.10

  # you can overwrite defaults here
  stage: dev
  region: us-west-1

functions:
  log-monitor:
    handler: monitor.handler
    events:
    - cloudwatchLog: '/aws/lambda/scratch'
#    role:
#      'Fn::GetAtt': [ S3ImageRekognitionRole, Arn ]

#resources:
#  Resources:
#    # Roles
#    S3ImageRekognitionRole:
#      Type: AWS::IAM::Role
#      Properties:
#        Path: /
#        RoleName: S3ImageRekognitionRole
#        AssumeRolePolicyDocument:
#          Version: '2012-10-17'
#          Statement:
#          - Effect: Allow
#            Action: sts:AssumeRole
#            Principal:
#              Service: lambda.amazonaws.com
#        ManagedPolicyArns:
#        - arn:aws:iam::aws:policy/AdministratorAccess
#
#        Policies:
#        - PolicyName: StoreImageLabelsInBucket
#          PolicyDocument:
#            Version: '2012-10-17'
#            Statement:
#            - Effect: Allow
#              Action:
#              - 's3:putObject'
#              Resource: arn:aws:s3:::rnrtempbucket/*
#        - PolicyName: ReadImageFromBucket
#          PolicyDocument:
#            Version: '2012-10-17'
#            Statement:
#            - Effect: Allow
#              Action:
#              - 's3:putObject'
#              Resource: arn:aws:s3:::rnrtempbucket/*
#        - PolicyName: RunRekognition
#          PolicyDocument:
#            Version: '2012-10-17'
#            Statement:
#            - Effect: Allow
#              Action:
#              - 'rekognition:*'
#              Resource: '*'



#
#resources:
#  Resources:
#    # Roles
#    S3ImageRekognitionRole: # role for Categories Lambda
#      Type: AWS::IAM::Role
#      Properties:
#        Path: /
#        RoleName: S3ImageRekognitionRole
#        AssumeRolePolicyDocument:
#          Version: '2012-10-17'
#          Statement:
#          - Effect: Allow
#            Action: sts:AssumeRole
#            Principal:
#              Service: lambda.amazonaws.com
##        ManagedPolicyArns:
##        - ${self:custom.private.teamPolicy}
#        Policies:
#        - PolicyName: StoreImageInBucket
#          PolicyDocument:
#            Version: '2012-10-17'
#            Statement:
#            - Effect: Allow
#              Action:
#              - 's3:putObject'
#              Resource: arn:aws:s3:::rnrtempbucket
